### ISSUE TITLE
Legge til særnorsk regel for ball i tak

### ISSUE THREAD

**Issue by vegardbus** [nvbf/spilleregler#2]
Som eit tillegg til paragraf 8 om ball ut bør vi legge til dette:
https://volleyball.no/nyheter/ballen-kan-na-berore-taket-i-alle-kamper/

Alle baller, med unntak av serven, skal spilles videre dersom de treffer taket eller andre gjenstander som er over bane- og friområde (spillområde).

Nedenfor nevnes noen spesifiseringer for dømming når ballen er ute eller om det dømmes omserve.

Ballen dømmes ute når: 
1. Ballen treffer taket eller en annen hindring over motstanderens spillområde.
2. Ballen treffer taket eller en annen hindring over lagets spillområde og passerer nettets vertikale linje og inn i motstanderens bane.
3. Ballen treffer taket eller en annen hindring etter lagets tredje slag.
4. Ballen treffer en nedsenket skillevegg (den er da å anse som en hvilken som helst annen vegg).
5. Ballen treffer taket tydelig utenfor lagets friområde.
6. Dersom en ball blir liggende stille på et hinder som er over lagets spillområde, skal det dømmes ball ut.

**Comment by hansfn** [comment]
Ja, det hadde vært flott å få dette inn. Jeg syns det er greit selv om vi sier at dette er "oversettelsen av de internasjonale reglene". Jeg kan lage en PR hvis du ikke har veldig lyst selv. Jeg tenker at "Ballen dømmes ute når" kanskje kan være en fotnote siden resten av reglene ikke har så utfyllende eksempler?

**Comment by vegardbus** [comment]
Supert - ja, lag gjerne ein PR på det, men eg tar gjerne ein titt på den for å sjå korleis ein litt meir omfattande PR fungerer for HTML-kode

**Comment by hansfn** [comment]
Da ser du at jeg har lagd en PR - #7. Jeg har brukt en fotnote for å unngå at punktet 8.4.2 blir så langt. Jeg har også et forslag til en liten endring av regelen som gjøre at noen av eksemplene egentlig ikke er nødvendig for å dømme riktig.
